apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 8080 # service port number
      targetPort: 80 # port number of the application running inside the container

# sudo kubectl describe svc nginx-service
# Name:              nginx-service
# Namespace:         default
# Labels:            <none>
# Annotations:       <none>
# Selector:          app=nginx-pod
# Type:              ClusterIP
# IP Families:       <none>
# IP:                10.105.33.153
# IPs:               10.105.33.153
# Port:              <unset>  8080/TCP
# TargetPort:        80/TCP
# Endpoints:         172.17.0.4:80,172.17.0.5:80
# Session Affinity:  None
# Events:            <none>
