apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

# sudo kubectl get svc
# NAME                    TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
# kubernetes              ClusterIP      10.96.0.1       <none>        443/TCP          2d21h
# mongo-express-service   LoadBalancer   10.105.56.236   <pending>     8080:30000/TCP   17s
# mongodb-service         ClusterIP      10.99.191.232   <none>        27017/TCP        63m


# ClusterIP will give a service an internal IP address
# LoadBalancer will also give a service an internal IP address, in addition to that it will also give an external IP address
