apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: busybox-container
    image: busybox
    volumeMounts:
      - name: config-dir
        mountPath: /etc/config
      - name: secret-dir
        mountPath: /etc/secret
      - name: persistent-storage
        mountPath: /var/lib/config
  volumes:
  - name: config-dir
    configMap:
      name: bb-configmap
  - name: secret-dir
    secret:
      secretName: bb-secret
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: bb-persistent-storage
